<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Using Include="Microsoft.AspNetCore.Builder" />
    <Using Include="Microsoft.AspNetCore.Http" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="Microsoft.Extensions.Configuration" />
    <ProjectReference Include="..\AgentHappey.Async\AgentHappey.Async.csproj" />
    <ProjectReference Include="..\Agents\AgentHappey.Agents.JSON\AgentHappey.Agents.JSON.csproj" />
  </ItemGroup>
</Project>
